/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IOptionalOnlyCaller,
  IOptionalOnlyCallerInterface,
} from "../../../../contracts/balancer-labs-0.8/interfaces/IOptionalOnlyCaller";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "enabled",
        type: "bool",
      },
    ],
    name: "OnlyCallerOptIn",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "isOnlyCallerEnabled",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "enabled",
        type: "bool",
      },
    ],
    name: "setOnlyCallerCheck",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "bool",
        name: "enabled",
        type: "bool",
      },
      {
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
    ],
    name: "setOnlyCallerCheckWithSignature",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IOptionalOnlyCaller__factory {
  static readonly abi = _abi;
  static createInterface(): IOptionalOnlyCallerInterface {
    return new utils.Interface(_abi) as IOptionalOnlyCallerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOptionalOnlyCaller {
    return new Contract(address, _abi, signerOrProvider) as IOptionalOnlyCaller;
  }
}
