/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as balancerLabs08 from "./balancer-labs-0.8";
export type { balancerLabs08 };
import type * as governance from "./governance";
export type { governance };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { FeeDistributor } from "./FeeDistributor";
export type { LDAOToken } from "./LDAOToken";
export type { VotingEscrow } from "./VotingEscrow";
