/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governorCopySol from "./Governor copy.sol";
export type { governorCopySol };
import type * as mygovernorSol from "./Mygovernor.sol";
export type { mygovernorSol };
import type * as compatibility from "./compatibility";
export type { compatibility };
import type * as extensions from "./extensions";
export type { extensions };
import type * as utils from "./utils";
export type { utils };
export type { Governor } from "./Governor";
export type { IGovernor } from "./IGovernor";
export type { TimelockController } from "./TimelockController";
