/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAuthentication } from "./IAuthentication";
export type { IOptionalOnlyCaller } from "./IOptionalOnlyCaller";
export type { ISignaturesValidator } from "./ISignaturesValidator";
